// <auto-generated />
using System;
using Kart.Wishlist.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Kart.Wishlist.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(WishlistDbContext))]
    partial class WishlistDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.HasPostgresExtension(modelBuilder, "pgcrypto");
            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Kart.Wishlist.Domain.Entities.WishlistAlertDedup", b =>
                {
                    b.Property<Guid>("DedupId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("dedup_id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<DateTimeOffset>("AlertedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("alerted_at");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("created_by");

                    b.Property<decimal>("PriceObserved")
                        .HasColumnType("numeric(12,2)")
                        .HasColumnName("price_observed");

                    b.Property<string>("Sku")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("sku");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<string>("UpdatedBy")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("updated_by");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("DedupId");

                    b.HasIndex("UserId", "Sku")
                        .HasDatabaseName("idx_wishlist_alert_dedup_user_sku");

                    b.HasIndex("UserId", "Sku", "PriceObserved")
                        .IsUnique()
                        .HasDatabaseName("uq_wishlist_alert_dedup");

                    b.ToTable("wishlist_alert_dedup", (string)null);
                });

            modelBuilder.Entity("Kart.Wishlist.Domain.Entities.WishlistEntry", b =>
                {
                    b.Property<Guid>("EntryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("entry_id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<DateTimeOffset>("AddedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("added_at");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("created_by");

                    b.Property<DateTimeOffset?>("LastAlertedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_alerted_at");

                    b.Property<decimal>("ReferencePrice")
                        .HasColumnType("numeric(12,2)")
                        .HasColumnName("reference_price");

                    b.Property<string>("Sku")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("sku");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("status");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<string>("UpdatedBy")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("updated_by");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("EntryId");

                    b.HasIndex("Status", "Sku")
                        .HasDatabaseName("idx_wishlist_entries_status_sku");

                    b.HasIndex("UserId", "Sku")
                        .IsUnique()
                        .HasDatabaseName("uq_wishlist_entries_user_sku");

                    b.HasIndex("UserId", "Status")
                        .HasDatabaseName("idx_wishlist_entries_user_status");

                    b.HasIndex(new[] { "Sku" }, "idx_wishlist_entries_sku")
                        .HasFilter("status = 'active'");

                    b.ToTable("wishlist_entries", null, t =>
                        {
                            t.HasCheckConstraint("ck_wishlist_entries_status", "status IN ('active', 'stale')");
                        });
                });

            modelBuilder.Entity("Kart.Wishlist.Domain.Outbox.WishlistOutboxEvent", b =>
                {
                    b.Property<Guid>("OutboxId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("outbox_id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("created_by");

                    b.Property<string>("EventType")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("event_type");

                    b.Property<DateTimeOffset>("OccurredAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("occurred_at");

                    b.Property<string>("Payload")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("payload");

                    b.Property<DateTimeOffset?>("ProjectedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("projected_at");

                    b.Property<DateTimeOffset?>("PublishedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("published_at");

                    b.Property<string>("Sku")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("sku");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<string>("UpdatedBy")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("updated_by");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("OutboxId");

                    b.HasIndex(new[] { "OccurredAt" }, "idx_wishlist_outbox_unprojected")
                        .HasFilter("projected_at IS NULL");

                    b.HasIndex(new[] { "OccurredAt" }, "idx_wishlist_outbox_unpublished")
                        .HasFilter("published_at IS NULL");

                    b.ToTable("wishlist_outbox_events", null, t =>
                        {
                            t.HasCheckConstraint("ck_wishlist_outbox_events_event_type", "event_type IN ('WishlistPriceAlertTriggered', 'WishlistEntryMutated')");
                        });
                });

            modelBuilder.Entity("Kart.Wishlist.Infrastructure.Auditing.WishlistAuditLogRecord", b =>
                {
                    b.Property<Guid>("EntryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("entry_id");

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("action");

                    b.Property<string>("ActorId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("actor_id");

                    b.Property<string>("ActorType")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("actor_type");

                    b.Property<string>("EntityId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("entity_id");

                    b.Property<string>("EntityType")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("entity_type");

                    b.Property<string>("MetadataJson")
                        .HasColumnType("jsonb")
                        .HasColumnName("metadata");

                    b.Property<DateTimeOffset>("OccurredAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("occurred_at");

                    b.Property<string>("ServiceName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("service_name");

                    b.HasKey("EntryId");

                    b.HasIndex("EntityType", "EntityId")
                        .HasDatabaseName("idx_wishlist_audit_log_entity");

                    b.ToTable("wishlist_audit_log", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
